export const INITIAL_DRIVER_OFFERS = [
  {
    id: 'DRV-101',
    type: 'driver_offer',
    maskedCode: 'CX-BP101',
    publicName: 'Chủ xe Lộc Ninh #101',
    phoneReal: '0988.234.567',
    direction: 'province_to_sg',
    from: 'Bù Đốp (Cây xăng Petrolimex 17, QL13)',
    to: 'Sài Gòn (Ngã tư Hàng Xanh / BX Miền Đông mới)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 - 06:00 Sáng',
    carType: 'Mitsubishi Xpander (Xe 7 chỗ)',
    capacity: 4,
    availableSeats: 3,
    basePricePerSeat: 180000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.95,
    completedCount: 142,
    perks: ['Không khói thuốc', 'Trọn gói xăng & cầu đường', 'Xe gia đình'],
    notes: 'Xe gia đình sạch sẽ, đón dọc QL13 tiện đường, không hút thuốc. Đi làm văn phòng văn minh.',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'DRV-102',
    type: 'driver_offer',
    maskedCode: 'CX-BP102',
    publicName: 'Chủ xe Lộc Ninh #102',
    phoneReal: '0913.889.922',
    direction: 'province_to_sg',
    from: 'Lộc Ninh (Chợ Ninh Thịnh / Ngã 3 Lộc Tấn)',
    to: 'Sài Gòn (Quận Tân Bình / Sân bay TSN)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Lộc Ninh',
    date: 'Hôm nay',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 - 08:00 Sáng',
    carType: 'Toyota Veloz Cross (Xe 7 chỗ)',
    capacity: 5,
    availableSeats: 4,
    basePricePerSeat: 200000,
    customDiscountPercent: 15,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.9,
    completedCount: 98,
    perks: ['Trọn gói xăng & cầu đường', 'Cốp rộng', 'Xe gia đình'],
    notes: 'Xe gia đình rộng rãi, cốp lớn để hành lý. Đón trả linh hoạt dọc tuyến, hai bên tự hẹn điểm.',
    createdAt: Date.now() - 3600000 * 4
  },
  {
    id: 'DRV-103',
    type: 'driver_offer',
    maskedCode: 'CX-PT103',
    publicName: 'Chủ xe Phan Thiết #103',
    phoneReal: '0977.556.334',
    direction: 'province_to_sg',
    from: 'Phan Thiết (Vòng xoay Suối Cát / BX Nam)',
    to: 'Sài Gòn (Nút giao An Phú / Quận 1)',
    routeCategory: 'Tuyến QL1A',
    hometown: 'Phan Thiết',
    date: 'Hôm nay',
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 - 06:00 Sáng',
    carType: 'Toyota Innova (Xe 7 chỗ)',
    capacity: 5,
    availableSeats: 4,
    basePricePerSeat: 190000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.85,
    completedCount: 67,
    perks: ['Chạy cao tốc Dầu Giây', 'Trọn gói xăng & cầu đường', 'Xe êm mát'],
    notes: 'Đi công tác SG hàng tuần, xe sạch máy lạnh, đón dọc QL1A và cao tốc.',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'DRV-110',
    type: 'driver_offer',
    maskedCode: 'CX-HN110',
    publicName: 'Chủ xe Hà Nội #110',
    phoneReal: '0984.883.750',
    direction: 'both',
    from: 'Hà Nội (Bến xe Mỹ Đình / Big C Thăng Long)',
    to: 'Hải Phòng (Bến xe Vĩnh Niệm / Nhà hát lớn)',
    routeCategory: 'Hà Nội ⇄ Hải Phòng',
    hometown: 'Hà Nội',
    date: 'Hôm nay',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 - 08:00 Sáng',
    carType: 'Toyota Corolla Cross (Xe 5 chỗ)',
    capacity: 4,
    availableSeats: 3,
    basePricePerSeat: 150000,
    customDiscountPercent: 10,
    depositPerSeat: 0,
    isVip: true,
    rating: 4.96,
    completedCount: 52,
    carCategory: 'family_car',
    waypointNote: 'Tiện đón trả dọc Cao tốc 5B Hà Nội - Hải Phòng, nút giao Vành đai 3',
    perks: ['Xe gia đình (Biển trắng)', 'Trọn gói vé cao tốc 5B & xăng', 'Không khói thuốc'],
    notes: 'Xe gia đình đi làm cuối tuần về Hải Phòng, chạy cao tốc 5B êm ái, đón trả linh hoạt.',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'DRV-111',
    type: 'driver_offer',
    maskedCode: 'CX-DN111',
    publicName: 'Bác tài Đà Nẵng #111',
    phoneReal: '0912.334.556',
    direction: 'both',
    from: 'Đà Nẵng (Cầu Rồng / Bến xe Trung tâm)',
    to: 'Huế (Bến xe Phía Nam / Trung tâm TP. Huế)',
    routeCategory: 'Đà Nẵng ⇄ Huế',
    hometown: 'Đà Nẵng',
    date: 'Hôm nay',
    timeSlot: '09:00-10:00',
    timeSlotLabel: '09:00 - 10:00 Sáng',
    carType: 'Ford Transit / Xpander (Xe 7 chỗ)',
    capacity: 6,
    availableSeats: 4,
    basePricePerSeat: 120000,
    customDiscountPercent: 10,
    depositPerSeat: 0,
    isVip: true,
    rating: 4.88,
    completedCount: 84,
    carCategory: 'convenient_trip',
    waypointNote: 'Tiện đón trả dọc Hầm Hải Vân, Lăng Cô, Phú Lộc',
    perks: ['Xe tiện chuyến (Biển vàng)', 'Trọn gói vé hầm & xăng dầu', 'Lái xe an toàn'],
    notes: 'Xe tiện chuyến chiều về rỗng khách, nhận ghép chia sẻ chi phí hầm & cầu đường.',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'DRV-104',
    type: 'driver_offer',
    maskedCode: 'CX-TN104',
    publicName: 'Chủ xe Tây Ninh #104',
    phoneReal: '0909.112.445',
    direction: 'province_to_sg',
    from: 'Trảng Bàng (Cổng KCN Trảng Bàng / QL22)',
    to: 'Sài Gòn (Bến xe An Sương / Tân Bình)',
    routeCategory: 'Tuyến QL22',
    hometown: 'Tây Ninh',
    date: 'Hôm nay',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 - 08:00 Sáng',
    carType: 'Kia Carnival (Xe 7 chỗ)',
    capacity: 6,
    availableSeats: 5,
    basePricePerSeat: 120000,
    customDiscountPercent: 15,
    depositPerSeat: 50000,
    isVip: false,
    rating: 4.7,
    completedCount: 34,
    perks: ['Không khói thuốc', 'Trọn gói xăng xe', 'Đón tận nơi'],
    notes: 'Đi làm KCN Củ Chi, ghép dọc QL22 tiện đường. Ghế bọc da êm ái.',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'DRV-105',
    type: 'driver_offer',
    maskedCode: 'CX-MT105',
    publicName: 'Chủ xe Mỹ Tho #105',
    phoneReal: '0365.778.991',
    direction: 'province_to_sg',
    from: 'Mỹ Tho (Bến xe Tiền Giang / Ngã 3 Trung Lương)',
    to: 'Sài Gòn (Bến xe Miền Tây / Quận 6)',
    routeCategory: 'Tuyến CT Trung Lương',
    hometown: 'Tiền Giang',
    date: 'Hôm nay',
    timeSlot: '09:00-10:00',
    timeSlotLabel: '09:00 - 10:00 Sáng',
    carType: 'Honda CR-V (Xe 5 chỗ)',
    capacity: 3,
    availableSeats: 2,
    basePricePerSeat: 100000,
    customDiscountPercent: 0,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.92,
    completedCount: 89,
    perks: ['Chạy cao tốc Trung Lương', 'Trọn gói xăng & cầu đường'],
    notes: 'Chạy cao tốc Trung Lương, nhanh 1 tiếng. Đón tại BX Mỹ Tho.',
    createdAt: Date.now() - 3600000 * 5
  },
  {
    id: 'DRV-106',
    type: 'driver_offer',
    maskedCode: 'CX-BH106',
    publicName: 'Chủ xe Biên Hòa #106',
    phoneReal: '0812.334.667',
    direction: 'province_to_sg',
    from: 'Biên Hòa (Ngã tư Amata / QL1K)',
    to: 'Sài Gòn (Cầu Bình Triệu / Hàng Xanh)',
    routeCategory: 'Tuyến QL1K',
    hometown: 'Đồng Nai',
    date: 'Hôm nay',
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 - 06:00 Sáng',
    carType: 'VinFast VF8 (Xe 5 chỗ điện)',
    capacity: 3,
    availableSeats: 2,
    basePricePerSeat: 80000,
    customDiscountPercent: 0,
    depositPerSeat: 50000,
    isVip: false,
    rating: 4.8,
    completedCount: 23,
    perks: ['Xe điện êm ái', 'Không mùi xăng', 'Ghế rộng'],
    notes: 'Xe điện VinFast, êm mát, không mùi xăng. Chuyến sáng sớm, giờ giấc hai bên tự thống nhất.',
    createdAt: Date.now() - 3600000 * 2
  }
];

export const INITIAL_PASSENGER_REQUESTS = [
  {
    id: 'REQ-201',
    type: 'passenger_request',
    maskedCode: 'KH-SG201',
    publicName: 'Khách đi khám Chợ Rẫy #201',
    phoneReal: '0945.123.889',
    direction: 'province_to_sg',
    from: 'Lộc Ninh (Chợ Lộc Ninh / KP Ninh Thịnh)',
    to: 'Sài Gòn (Bệnh Viện Chợ Rẫy / Quận 5)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Lộc Ninh',
    date: 'Hôm nay',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 - 08:00 Sáng',
    seatsNeeded: 2,
    expectedPrice: 180000,
    depositPerSeat: 50000,
    notes: 'Cần ghép 2 ghế đi tái khám, sẵn sàng cọc 100k cho 2 người. Lịch sự, không say xe.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'REQ-202',
    type: 'passenger_request',
    maskedCode: 'KH-SG202',
    publicName: 'Khách về quê #202',
    phoneReal: '0968.445.112',
    direction: 'sg_to_province',
    from: 'Sài Gòn (Ngã 4 Thủ Đức / Xa Lộ Hà Nội)',
    to: 'Bình Phước (Cổng chào TX. Bình Long / QL13)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    timeSlot: '17:00-18:00',
    timeSlotLabel: '17:00 - 18:00 Chiều',
    seatsNeeded: 1,
    expectedPrice: 170000,
    depositPerSeat: 50000,
    notes: 'Cuối tuần về quê, ghép xe dọc QL13 có 1 balo nhỏ gọn gàng.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'REQ-203',
    type: 'passenger_request',
    maskedCode: 'KH-VT203',
    publicName: 'Khách đi Vũng Tàu #203',
    phoneReal: '0933.221.887',
    direction: 'sg_to_province',
    from: 'Sài Gòn (Quận 7 / Crescent Mall)',
    to: 'Vũng Tàu (Bãi Sau / Tượng Chúa Kito)',
    routeCategory: 'Tuyến QL51',
    hometown: 'Vũng Tàu',
    date: 'Hôm nay',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 - 08:00 Sáng',
    seatsNeeded: 3,
    expectedPrice: 160000,
    depositPerSeat: 50000,
    notes: 'Gia đình 3 người đi biển cuối tuần, có 2 balo + 1 túi nhỏ.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'REQ-204',
    type: 'passenger_request',
    maskedCode: 'KH-PT204',
    publicName: 'Khách về Phan Thiết #204',
    phoneReal: '0899.443.556',
    direction: 'sg_to_province',
    from: 'Sài Gòn (Bến xe Miền Đông mới / TP. Thủ Đức)',
    to: 'Phan Thiết (Mũi Né / Đồi Cát Bay)',
    routeCategory: 'Tuyến QL1A',
    hometown: 'Bình Thuận',
    date: 'Hôm nay',
    timeSlot: '15:00-16:00',
    timeSlotLabel: '15:00 - 16:00 Chiều',
    seatsNeeded: 1,
    expectedPrice: 180000,
    depositPerSeat: 50000,
    notes: 'Sinh viên về quê, hành lý gọn.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'REQ-205',
    type: 'passenger_request',
    maskedCode: 'KH-BT205',
    publicName: 'Khách về Bến Tre #205',
    phoneReal: '0708.991.223',
    direction: 'sg_to_province',
    from: 'Bến xe Miền Tây (Q. Bình Tân)',
    to: 'TP Bến Tre',
    routeCategory: 'Tuyến QL60',
    hometown: 'Bến Tre',
    date: 'Hôm nay',
    timeSlot: '13:00-14:00',
    timeSlotLabel: '13:00 - 14:00 Chiều',
    seatsNeeded: 2,
    expectedPrice: 120000,
    depositPerSeat: 50000,
    notes: 'Hai chị em về thăm ngoại, cần xe sạch sẽ, không mùi thuốc lá.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 4
  }
];

export const INITIAL_BOOKED_ESCROWS = [
  {
    escrowId: 'CX-7821',
    targetItem: {
      id: 'DRV-102',
      type: 'driver_offer',
      publicName: 'Chủ xe Lộc Ninh #102',
      phoneReal: '0913.889.922',
      from: 'Chợ Lộc Ninh (Bình Phước)',
      to: 'Sài Gòn (Quận Tân Bình / Phú Nhuận)',
      timeSlotLabel: '07:00 - 08:00 Sáng',
      carType: 'Toyota Veloz Cross (Xe 7 chỗ)'
    },
    commitmentType: 'zalo_direct',
    partyRole: 'Khách đồng hành cùng Chủ Xe',
    contactName: 'Chủ xe Lộc Ninh #102',
    contactPhone: '0913.889.922',
    seats: 2,
    depositAmount: 0,
    fullTripAmount: 400000,
    paidToEscrow: 0,
    remainingCash: 400000,
    totalDeal: 400000,
    timeSlot: '07:00 - 08:00 Sáng',
    from: 'Chợ Lộc Ninh (Bình Phước)',
    to: 'Sài Gòn (Quận Tân Bình / Phú Nhuận)',
    status: 'zalo_active',
    bothConfirmed: true,
    createdAt: 'Hôm nay, 06:20'
  },
  {
    escrowId: 'CX-5120',
    targetItem: {
      id: 'DRV-101',
      type: 'driver_offer',
      publicName: 'Chủ xe Chơn Thành #101',
      phoneReal: '0908.123.456',
      from: 'Bến Xe Miền Đông Cũ',
      to: 'Chợ Chơn Thành (Bình Phước)',
      timeSlotLabel: '14:00 - 15:00 Chiều',
      carType: 'Mitsubishi Xpander'
    },
    commitmentType: 'zalo_direct',
    partyRole: 'Khách ghép xe Chủ Xe',
    contactName: 'Chủ xe Chơn Thành #101',
    contactPhone: '0908.123.456',
    seats: 1,
    depositAmount: 0,
    fullTripAmount: 180000,
    paidToEscrow: 0,
    remainingCash: 180000,
    totalDeal: 180000,
    timeSlot: '14:00 - 15:00 Chiều',
    from: 'Bến Xe Miền Đông Cũ',
    to: 'Chợ Chơn Thành (Bình Phước)',
    status: 'zalo_active',
    bothConfirmed: true,
    createdAt: 'Hôm qua'
  }
];
