export const INITIAL_DRIVER_OFFERS = [
  {
    id: 'DRV-101',
    type: 'driver_offer',
    maskedCode: 'CX-101',
    publicName: 'Chủ xe CX-101',
    realName: 'Anh Tuấn',
    driverRealName: 'Anh Tuấn',
    phoneReal: '0900.000.019',
    direction: 'province_to_sg',
    from: 'Bù Đốp (Cây xăng Petrolimex 17, QL13)',
    to: 'Sài Gòn (Ngã tư Hàng Xanh / BX Miền Đông mới)',
    originHubId: 'hub_ql13_budop',
    destinationHubId: 'hub_ql13_hang_xanh',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 – 06:00',
    carType: 'Mitsubishi Xpander (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 3,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 240000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 5.0,
    completedCount: 142,
    perks: ['Không khói thuốc', 'Trọn gói xăng & cầu đường', 'Xe gia đình', 'Nhận gửi đồ tiện chuyến'],
    carPhotos: [
      {
        angle: 'front',
        label: 'Góc Trước (Đầu xe)',
        url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
        caption: 'Đầu xe sáng đẹp, đèn LED hiện đại'
      },
      {
        angle: 'back',
        label: 'Góc Sau (Đuôi xe & Cốp)',
        url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
        caption: 'Đuôi xe sạch sẽ, cốp rộng để hành lý'
      },
      {
        angle: 'side',
        label: 'Góc Thân xe (Bên hông)',
        url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
        caption: 'Thân xe nguyên bản, không trầy xước'
      },
      {
        angle: 'interior',
        label: 'Nội thất & Ghế ngồi',
        url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
        caption: 'Nội thất bọc da êm ái, máy lạnh 2 giàn'
      },
      {
        angle: 'trunk',
        label: 'Khoang cốp để đồ',
        url: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
        caption: 'Khoang hành lý rộng rãi, có thể hạ hàng ghế 3'
      }
    ],
    hasCarPhotos: true,
    plateMask: '93A - ***.86',
    fullPlate: '93A - 541.86',
    plate: '93A - 541.86',
    plateType: 'white',
    isServiceVehicle: false,
    notes: 'Xe gia đình sạch sẽ, đón dọc QL13 tiện đường, không hút thuốc. Cốp rộng nhận gửi thêm thùng xốp nông sản quê.',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'DRV-105',
    type: 'driver_offer',
    maskedCode: 'CX-105',
    publicName: 'Chủ xe dịch vụ CX-105',
    phoneReal: '0900.000.035',
    direction: 'both',
    from: 'Sài Gòn (Sân bay Tân Sơn Nhất / Hàng Xanh)',
    to: 'Bình Phước (Lái Thiêu ⇄ Thủ Dầu Một ⇄ Chơn Thành)',
    originHubId: 'hub_ql13_san_bay_tsn',
    destinationHubId: 'hub_ql13_nga4_chon_thanh',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Dương',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '16:00-18:00',
    timeSlotLabel: '16:00 – 18:00',
    carType: 'Mitsubishi Xpander (Xe 7 chỗ)',
    carCategory: 'convenient_trip',
    plateType: 'yellow',
    isServiceVehicle: true,
    capacity: 7,
    availableSeats: 5,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box', 'bulky_cargo'],
    basePricePerSeat: 130000,
    charterPrice: 300000,
    depositPerSeat: 0,
    isVip: true,
    rating: 4.95,
    completedCount: 215,
    plateMask: '61E - ***.24',
    fullPlate: '61E - 482.24',
    plate: '61E - 482.24',
    perks: ['Xe dịch vụ (Biển vàng)', 'Tiện chuyến chiều về rỗng', 'Đón trả tận ngõ', 'Nhiều vali hành lý', 'Bao xe trọn gói 300k'],
    serviceNote: 'Xe 7 chỗ rộng rãi chiều về từ TSN, đón tận ngõ, nhận ghép 100k/ghế hoặc bao nguyên xe 300k.',
    notes: 'Xe 7 chỗ rộng rãi chiều về rỗng từ Sân bay TSN, nhận đón trả tận ngõ quanh Lái Thiêu, Thủ Dầu Một, Bến Cát, Chơn Thành.',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'DRV-102',
    type: 'driver_offer',
    maskedCode: 'CX-102',
    publicName: 'Chủ xe H. (#102)',
    realName: 'Anh Hùng',
    driverRealName: 'Anh Hùng',
    phoneReal: '0900.000.013',
    direction: 'province_to_sg',
    from: 'Lộc Ninh (Chợ Ninh Thịnh / Ngã 3 Lộc Tấn)',
    to: 'Sài Gòn (Quận Tân Bình / Sân bay TSN)',
    originHubId: 'hub_ql13_cho_loc_ninh',
    destinationHubId: 'hub_ql13_san_bay_tsn',
    routeCategory: 'Tuyến QL13',
    hometown: 'Lộc Ninh',
    date: 'Ngày mai',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 – 08:00',
    isRecurringWeekly: true,
    carType: 'Toyota Veloz Cross (Xe 7 chỗ)',
    plateType: 'white',
    isServiceVehicle: false,
    capacity: 7,
    availableSeats: 4,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 215000,
    customDiscountPercent: 15,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.9,
    completedCount: 98,
    perks: ['Trọn gói xăng & cầu đường', 'Cốp rộng', 'Xe gia đình', 'Nhận gửi bưu phẩm'],
    photos: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1509000000103-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80'
    ],
    carPhotoUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    carPhotos: [
      {
        angle: 'front',
        label: 'Góc Trước (Đầu xe)',
        url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
        caption: 'Đầu xe gia đình 7 chỗ sáng bóng, đèn LED hiện đại'
      },
      {
        angle: 'side',
        label: 'Góc Thân xe (Bên hông)',
        url: 'https://images.unsplash.com/photo-1509000000103-7e6692767b70?auto=format&fit=crop&w=800&q=80',
        caption: 'Thân xe màu trắng sạch sẽ, không trầy xước'
      },
      {
        angle: 'back',
        label: 'Góc Sau (Đuôi xe & Cốp)',
        url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
        caption: 'Đuôi xe nguyên bản, camera lùi an toàn'
      },
      {
        angle: 'interior',
        label: 'Nội thất & Ghế ngồi',
        url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
        caption: 'Nội thất ghế bọc da sạch sẽ, không mùi thuốc lá'
      },
      {
        angle: 'trunk',
        label: 'Khoang cốp để đồ',
        url: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
        caption: 'Cốp xe 7 chỗ rộng rãi, chứa thoải mái 2-3 vali lớn'
      }
    ],
    hasCarPhotos: true,
    plateMask: '93A - ***.52',
    fullPlate: '93A - 283.52',
    plate: '93A - 283.52',
    notes: 'Xe gia đình rộng rãi, cốp lớn để hành lý. Đón trả linh hoạt dọc tuyến, nhận kèm đồ gọn/thùng xốp.',
    createdAt: Date.now() - 3600000 * 4
  },
  {
    id: 'DRV-115',
    type: 'driver_offer',
    maskedCode: 'CX-115',
    publicName: 'Chủ xe CX-115',
    phoneReal: '0900.000.035',
    direction: 'both',
    from: 'Chơn Thành (Ngã 4 Chơn Thành / QL13, Bình Phước)',
    to: 'Rạch Giá (Bến xe Rạch Sỏi / TP. Rạch Giá, Kiên Giang)',
    originHubId: 'hub_n2_chon_thanh',
    destinationHubId: 'hub_n2_rach_gia',
    routeCategory: 'Tuyến N2 - Kiên Giang',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 – 06:00',
    carType: 'Kia K250 (Xe tải mui bạt 2.4T)',
    vehicleType: 'truck_light',
    capacity: 2,
    availableSeats: 1,
    hasCargoBed: true,
    isCargoVehicle: true,
    cargoBedCapacityKg: 2400,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box', 'bulky_cargo', 'motorcycle', 'half_truck', 'full_truck'],
    basePricePerSeat: 450000,
    customDiscountPercent: 10,
    depositPerSeat: 0,
    isVip: true,
    rating: 4.95,
    completedCount: 68,
    carCategory: 'convenient_trip',
    waypointNote: 'Chạy Tuyến N2 qua Bến Cát, Hậu Nghĩa (Đức Hòa), Thạnh Hóa, Tháp Mười, Cầu Vàm Cống, Lộ Tẻ, Rạch Giá',
    perks: ['Thùng xe 2.4T sạch sẽ', 'Nhận chở xe máy có chằng buộc', 'Trọn gói cầu đường N2 & Vàm Cống'],
    notes: 'Chở nông sản Bình Phước về Miền Tây giao xong quay đầu rỗng thùng. Nhận chở xe máy về quê, nông sản vài tạ đến 1 tấn, hoặc bao trọn thùng xe tải 2.4T giá mềm chia sẻ chi phí.',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'DRV-116',
    type: 'driver_offer',
    maskedCode: 'CX-116',
    publicName: 'Chủ xe CX-116',
    phoneReal: '0900.000.041',
    direction: 'province_to_sg',
    from: 'Tân Tiến / Lộc Hiệp (Bù Đốp - Lộc Ninh)',
    to: 'Sài Gòn (Ngã 4 Bình Phước / BX Miền Đông)',
    originHubId: 'hub_ql13_tan_tien',
    destinationHubId: 'hub_ql13_nga4_binh_phuoc',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '09:00-10:00',
    timeSlotLabel: '09:00 – 10:00',
    carType: 'Toyota Fortuner (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 3,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 235000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.93,
    completedCount: 115,
    perks: ['Xe Fortuner gầm cao', 'Trọn gói xăng & cầu đường', 'Không hút thuốc'],
    notes: 'Xe Fortuner gầm cao êm ái, đón từ Tân Tiến qua Lộc Hiệp ra Ngã 3 Lộc Tấn theo QL13 về Sài Gòn.',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'DRV-117',
    type: 'driver_offer',
    maskedCode: 'CX-117',
    publicName: 'Chủ xe CX-117',
    phoneReal: '0900.000.042',
    direction: 'province_to_sg',
    from: 'TX. Bình Long (Vòng xoay An Lộc / Tân Khai)',
    to: 'Sài Gòn (Cầu Bình Triệu / Ngã tư Hàng Xanh)',
    originHubId: 'hub_ql13_binh_long',
    destinationHubId: 'hub_ql13_binh_trieu',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '13:30-14:30',
    timeSlotLabel: '13:30 – 14:30',
    carType: 'Hyundai SantaFe (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 4,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 175000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.97,
    completedCount: 138,
    perks: ['Xe gia đình 7 chỗ', 'Máy lạnh êm', 'Đón đúng giờ'],
    notes: 'Xe gia đình 7 chỗ đi đầu giờ chiều, điều hòa mát rượi, đón dọc QL13 từ Bình Long, Tân Khai, Chơn Thành.',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'DRV-118',
    type: 'driver_offer',
    maskedCode: 'CX-118',
    publicName: 'Chủ xe CX-118',
    phoneReal: '0900.000.043',
    direction: 'province_to_sg',
    from: 'Chơn Thành (Ngã 4 Chơn Thành / KCN Bàu Bàng)',
    to: 'Sài Gòn (Ngã tư Hàng Xanh / Quận 1)',
    originHubId: 'hub_ql13_nga4_chon_thanh',
    destinationHubId: 'hub_ql13_hang_xanh',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '17:00-18:00',
    timeSlotLabel: '17:00 – 18:00',
    carType: 'Mazda CX-5 (Xe 5 chỗ)',
    capacity: 4,
    availableSeats: 2,
    basePricePerSeat: 120000,
    customDiscountPercent: 0,
    depositPerSeat: 0,
    isVip: true,
    rating: 5.0,
    completedCount: 79,
    perks: ['Xe gia đình 5 chỗ', 'Không mùi xăng', 'Chạy đúng giờ'],
    notes: 'Tan tầm từ Chơn Thành về Sài Gòn, xe 5 chỗ sạch sẽ không hút thuốc, trả dọc Hàng Xanh/Q1.',
    createdAt: Date.now() - 3600000 * 1
  }
];

export const INITIAL_PASSENGER_REQUESTS = [
  {
    id: 'REQ-201',
    type: 'passenger_request',
    maskedCode: 'KX-201',
    publicName: 'Khách KX-201',
    phoneReal: '0900.000.015',
    direction: 'province_to_sg',
    from: 'Lộc Ninh (Chợ Lộc Ninh / KP Ninh Thịnh)',
    to: 'Sài Gòn (Bệnh Viện Chợ Rẫy / Quận 5)',
    originHubId: 'hub_ql13_cho_loc_ninh',
    destinationHubId: 'hub_ql13_cho_ray',
    routeCategory: 'Tuyến QL13',
    hometown: 'Lộc Ninh',
    date: 'Ngày mai',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 – 08:00',
    isRecurringWeekly: true,
    seatsNeeded: 2,
    expectedPrice: 220000,
    depositPerSeat: 50000,
    notes: 'Cần ghép 2 ghế đi tái khám, sẵn sàng cọc 100k cho 2 người. Lịch sự, không say xe.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'REQ-202',
    type: 'passenger_request',
    maskedCode: 'KX-202',
    publicName: 'Khách KX-202',
    phoneReal: '0900.000.016',
    direction: 'sg_to_province',
    from: 'Sài Gòn (Ngã 4 Thủ Đức / Xa Lộ Hà Nội)',
    to: 'Bình Phước (Cổng chào TX. Bình Long / QL13)',
    originHubId: 'hub_ql13_van_phuc_city',
    destinationHubId: 'hub_ql13_tthc_binh_long',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    timeSlot: '17:00-18:00',
    timeSlotLabel: '17:00 – 18:00',
    seatsNeeded: 1,
    expectedPrice: 180000,
    depositPerSeat: 50000,
    notes: 'Cuối tuần về quê, ghép xe dọc QL13 có 1 balo nhỏ gọn gàng.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 2
  }
];

export const INITIAL_BOOKED_ESCROWS = [];
