export const INITIAL_DRIVER_OFFERS = [
  {
    id: 'DRV-101',
    type: 'driver_offer',
    maskedCode: 'CX-101',
    publicName: 'Chủ xe CX-101',
    phoneReal: '0900.000.019',
    direction: 'province_to_sg',
    from: 'Bù Đốp (Cây xăng Petrolimex 17, QL13)',
    to: 'Sài Gòn (Ngã tư Hàng Xanh / BX Miền Đông mới)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 – 06:00',
    carType: 'Mitsubishi Xpander (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 3,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 180000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 5.0,
    completedCount: 142,
    perks: ['Không khói thuốc', 'Trọn gói xăng & cầu đường', 'Xe gia đình', 'Nhận gửi đồ tiện chuyến'],
    carPhotos: [
      {
        angle: 'front',
        label: 'Góc Trước (Đầu xe)',
        url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
        caption: 'Đầu xe sáng đẹp, đèn LED hiện đại'
      },
      {
        angle: 'back',
        label: 'Góc Sau (Đuôi xe & Cốp)',
        url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
        caption: 'Đuôi xe sạch sẽ, cốp rộng để hành lý'
      },
      {
        angle: 'side',
        label: 'Góc Thân xe (Bên hông)',
        url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
        caption: 'Thân xe nguyên bản, không trầy xước'
      },
      {
        angle: 'interior',
        label: 'Nội thất & Ghế ngồi',
        url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
        caption: 'Nội thất bọc da êm ái, máy lạnh 2 giàn'
      },
      {
        angle: 'trunk',
        label: 'Khoang cốp để đồ',
        url: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
        caption: 'Khoang hành lý rộng rãi, có thể hạ hàng ghế 3'
      }
    ],
    hasCarPhotos: true,
    plateMask: '93A - ***.86',
    notes: 'Xe gia đình sạch sẽ, đón dọc QL13 tiện đường, không hút thuốc. Cốp rộng nhận gửi thêm thùng xốp nông sản quê.',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'DRV-102',
    type: 'driver_offer',
    maskedCode: 'CX-102',
    publicName: 'Chủ xe CX-102',
    phoneReal: '0900.000.013',
    direction: 'province_to_sg',
    from: 'Lộc Ninh (Chợ Ninh Thịnh / Ngã 3 Lộc Tấn)',
    to: 'Sài Gòn (Quận Tân Bình / Sân bay TSN)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Lộc Ninh',
    date: 'Ngày mai',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 – 08:00',
    isRecurringWeekly: true,
    carType: 'Toyota Veloz Cross (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 4,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 200000,
    customDiscountPercent: 15,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.9,
    completedCount: 98,
    perks: ['Trọn gói xăng & cầu đường', 'Cốp rộng', 'Xe gia đình', 'Nhận gửi bưu phẩm'],
    carPhotos: [
      {
        angle: 'front',
        label: 'Góc Trước (Đầu xe)',
        url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
        caption: 'Mặt trước thể thao, đèn chiếu sáng sắc nét'
      },
      {
        angle: 'back',
        label: 'Góc Sau (Đuôi xe & Cốp)',
        url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
        caption: 'Cốp sau rộng, mở nhẹ nhàng'
      },
      {
        angle: 'side',
        label: 'Góc Thân xe (Bên hông)',
        url: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=800&q=80',
        caption: 'Dáng xe cao ráo, gầm thoáng'
      },
      {
        angle: 'interior',
        label: 'Nội thất & Ghế ngồi',
        url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80',
        caption: 'Ghế da phối nỉ êm ái, sạch sẽ không mùi thuốc'
      }
    ],
    hasCarPhotos: true,
    plateMask: '93A - ***.52',
    notes: 'Xe gia đình rộng rãi, cốp lớn để hành lý. Đón trả linh hoạt dọc tuyến, nhận kèm đồ gọn/thùng xốp.',
    createdAt: Date.now() - 3600000 * 4
  },
  {
    id: 'DRV-104',
    type: 'driver_offer',
    maskedCode: 'CX-104',
    publicName: 'Chủ xe CX-104',
    phoneReal: '0900.000.021',
    direction: 'province_to_sg',
    from: 'Đồng Xoài (Tượng đài Chiến Thắng / QL14)',
    to: 'Sài Gòn (Thủ Đức / Xa lộ Hà Nội)',
    routeCategory: 'Tuyến QL14',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '07:00-09:00',
    timeSlotLabel: '07:00 – 09:00',
    carType: 'Ford Ranger Wildtrak (Xe bán tải)',
    vehicleType: 'pickup',
    hasCargoBed: true,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box', 'bulky_cargo'],
    capacity: 5,
    availableSeats: 3,
    basePricePerSeat: 160000,
    depositPerSeat: 0,
    isVip: true,
    rating: 5.0,
    completedCount: 84,
    perks: ['Xe bán tải có nắp thùng', 'Nhận chở đồ chuyển trọ', 'Thùng chở hàng ~800kg'],
    notes: 'Xe bán tải Ford Ranger thùng sau rộng rãi có nắp cuộn chống mưa. Nhận chở đồ cồng kềnh, chuyển trọ sinh viên, thùng xốp nông sản dọc QL14.',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'DRV-103',
    type: 'driver_offer',
    maskedCode: 'CX-103',
    publicName: 'Chủ xe CX-103',
    phoneReal: '0900.000.017',
    direction: 'province_to_sg',
    from: 'Phan Thiết (Vòng xoay Suối Cát / BX Nam)',
    to: 'Sài Gòn (Nút giao An Phú / Quận 1)',
    routeCategory: 'Tuyến QL1A',
    hometown: 'Phan Thiết',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 – 06:00',
    carType: 'Toyota Innova (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 4,
    basePricePerSeat: 190000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.85,
    completedCount: 67,
    perks: ['Chạy cao tốc Dầu Giây', 'Trọn gói xăng & cầu đường', 'Xe êm mát'],
    notes: 'Đi công tác SG hàng tuần, xe sạch máy lạnh, đón dọc QL1A và cao tốc.',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'DRV-110',
    type: 'driver_offer',
    maskedCode: 'CX-110',
    publicName: 'Chủ xe CX-110',
    phoneReal: '0984.883.750',
    direction: 'both',
    from: 'Hà Nội (Bến xe Mỹ Đình / Big C Thăng Long)',
    to: 'Hải Phòng (Bến xe Vĩnh Niệm / Nhà hát lớn)',
    routeCategory: 'Hà Nội ⇄ Hải Phòng',
    hometown: 'Hà Nội',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 – 08:00',
    carType: 'Toyota Corolla Cross (Xe 5 chỗ)',
    capacity: 4,
    availableSeats: 3,
    basePricePerSeat: 150000,
    customDiscountPercent: 10,
    depositPerSeat: 0,
    isVip: true,
    rating: 4.96,
    completedCount: 52,
    carCategory: 'family_car',
    waypointNote: 'Tiện đón trả dọc Cao tốc 5B Hà Nội - Hải Phòng, nút giao Vành đai 3',
    perks: ['Xe gia đình (Biển trắng)', 'Trọn gói phí cao tốc 5B & xăng', 'Không khói thuốc'],
    notes: 'Xe gia đình đi làm cuối tuần về Hải Phòng, chạy cao tốc 5B êm ái, đón trả linh hoạt.',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'DRV-111',
    type: 'driver_offer',
    maskedCode: 'CX-111',
    publicName: 'Chủ xe CX-111',
    phoneReal: '0900.000.024',
    direction: 'both',
    from: 'Đà Nẵng (Cầu Rồng / Bến xe Trung tâm)',
    to: 'Huế (Bến xe Phía Nam / Trung tâm TP. Huế)',
    routeCategory: 'Đà Nẵng ⇄ Huế',
    hometown: 'Đà Nẵng',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '09:00-10:00',
    timeSlotLabel: '09:00 – 10:00',
    carType: 'Ford Transit / Xpander (Xe 7 chỗ)',
    capacity: 6,
    availableSeats: 4,
    basePricePerSeat: 120000,
    customDiscountPercent: 10,
    depositPerSeat: 0,
    isVip: true,
    rating: 4.88,
    completedCount: 84,
    carCategory: 'convenient_trip',
    waypointNote: 'Tiện đón trả dọc Hầm Hải Vân, Lăng Cô, Phú Lộc',
    perks: ['Xe tiện chuyến (Biển vàng)', 'Trọn gói phí hầm & xăng dầu', 'Lái xe an toàn'],
    notes: 'Xe tiện chuyến chiều về rỗng khách, nhận ghép chia sẻ chi phí hầm & cầu đường.',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'DRV-115',
    type: 'driver_offer',
    maskedCode: 'CX-115',
    publicName: 'Chủ xe CX-115',
    phoneReal: '0900.000.035',
    direction: 'both',
    from: 'Chơn Thành (Ngã 4 Chơn Thành / QL13, Bình Phước)',
    to: 'Rạch Giá (Bến xe Rạch Sỏi / TP. Rạch Giá, Kiên Giang)',
    routeCategory: 'Tuyến N2 - Kiên Giang',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 – 06:00',
    carType: 'Kia K250 (Xe tải mui bạt 2.4T)',
    vehicleType: 'truck_light',
    capacity: 2,
    availableSeats: 1,
    hasCargoBed: true,
    isCargoVehicle: true,
    cargoBedCapacityKg: 2400,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box', 'bulky_cargo', 'motorcycle', 'half_truck', 'full_truck'],
    basePricePerSeat: 260000,
    customDiscountPercent: 10,
    depositPerSeat: 0,
    isVip: true,
    rating: 4.95,
    completedCount: 68,
    carCategory: 'convenient_trip',
    waypointNote: 'Chạy Tuyến N2 qua Bến Cát, Hậu Nghĩa (Đức Hòa), Thạnh Hóa, Tháp Mười, Cầu Vàm Cống, Lộ Tẻ, Rạch Giá',
    perks: ['Thùng xe 2.4T sạch sẽ', 'Nhận chở xe máy có chằng buộc', 'Trọn gói cầu đường N2 & Vàm Cống'],
    notes: 'Chở nông sản Bình Phước về Miền Tây giao xong quay đầu rỗng thùng. Nhận chở xe máy về quê, nông sản vài tạ đến 1 tấn, hoặc bao trọn thùng xe tải 2.4T giá mềm chia sẻ chi phí.',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'DRV-116',
    type: 'driver_offer',
    maskedCode: 'CX-116',
    publicName: 'Chủ xe CX-116',
    phoneReal: '0900.000.041',
    direction: 'province_to_sg',
    from: 'Tân Tiến / Lộc Hiệp (Bù Đốp - Lộc Ninh)',
    to: 'Sài Gòn (Ngã 4 Bình Phước / BX Miền Đông)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '09:00-10:00',
    timeSlotLabel: '09:00 – 10:00',
    carType: 'Toyota Fortuner (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 3,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 180000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.93,
    completedCount: 115,
    perks: ['Xe Fortuner gầm cao', 'Trọn gói xăng & cầu đường', 'Không hút thuốc'],
    notes: 'Xe Fortuner gầm cao êm ái, đón từ Tân Tiến qua Lộc Hiệp ra Ngã 3 Lộc Tấn theo QL13 về Sài Gòn.',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'DRV-117',
    type: 'driver_offer',
    maskedCode: 'CX-117',
    publicName: 'Chủ xe CX-117',
    phoneReal: '0900.000.042',
    direction: 'province_to_sg',
    from: 'TX. Bình Long (Vòng xoay An Lộc / Tân Khai)',
    to: 'Sài Gòn (Cầu Bình Triệu / Ngã tư Hàng Xanh)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '13:30-14:30',
    timeSlotLabel: '13:30 – 14:30',
    carType: 'Hyundai SantaFe (Xe 7 chỗ)',
    capacity: 7,
    availableSeats: 4,
    acceptsParcel: true,
    cargoTypes: ['compact_parcel', 'produce_box'],
    basePricePerSeat: 150000,
    customDiscountPercent: 10,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.97,
    completedCount: 138,
    perks: ['Xe gia đình 7 chỗ', 'Máy lạnh êm', 'Đón đúng giờ'],
    notes: 'Xe gia đình 7 chỗ đi đầu giờ chiều, điều hòa mát rượi, đón dọc QL13 từ Bình Long, Tân Khai, Chơn Thành.',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'DRV-118',
    type: 'driver_offer',
    maskedCode: 'CX-118',
    publicName: 'Chủ xe CX-118',
    phoneReal: '0900.000.043',
    direction: 'province_to_sg',
    from: 'Chơn Thành (Ngã 4 Chơn Thành / KCN Bàu Bàng)',
    to: 'Sài Gòn (Ngã tư Hàng Xanh / Quận 1)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    isRecurringWeekly: true,
    timeSlot: '17:00-18:00',
    timeSlotLabel: '17:00 – 18:00',
    carType: 'Mazda CX-5 (Xe 5 chỗ)',
    capacity: 4,
    availableSeats: 2,
    basePricePerSeat: 120000,
    customDiscountPercent: 0,
    depositPerSeat: 0,
    isVip: true,
    rating: 5.0,
    completedCount: 79,
    perks: ['Xe gia đình 5 chỗ', 'Không mùi xăng', 'Chạy đúng giờ'],
    notes: 'Tan tầm từ Chơn Thành về Sài Gòn, xe 5 chỗ sạch sẽ không hút thuốc, trả dọc Hàng Xanh/Q1.',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'DRV-108',
    type: 'driver_offer',
    maskedCode: 'CX-108',
    publicName: 'Chủ xe CX-108',
    phoneReal: '0900.000.012',
    direction: 'province_to_sg',
    from: 'Trảng Bàng (Cổng KCN Trảng Bàng / QL22)',
    to: 'Sài Gòn (Bến xe An Sương / Tân Bình)',
    routeCategory: 'Tuyến QL22',
    hometown: 'Tây Ninh',
    date: 'Hôm nay',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 – 08:00',
    carType: 'Kia Carnival (Xe 7 chỗ)',
    capacity: 6,
    availableSeats: 5,
    basePricePerSeat: 120000,
    customDiscountPercent: 15,
    depositPerSeat: 50000,
    isVip: false,
    rating: 4.7,
    completedCount: 34,
    perks: ['Không khói thuốc', 'Trọn gói xăng xe', 'Đón tận nơi'],
    notes: 'Đi làm KCN Củ Chi, ghép dọc QL22 tiện đường. Ghế bọc da êm ái.',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'DRV-105',
    type: 'driver_offer',
    maskedCode: 'CX-105',
    publicName: 'Chủ xe CX-105',
    phoneReal: '0900.000.011',
    direction: 'province_to_sg',
    from: 'Mỹ Tho (Bến xe Tiền Giang / Ngã 3 Trung Lương)',
    to: 'Sài Gòn (Bến xe Miền Tây / Quận 6)',
    routeCategory: 'Tuyến CT Trung Lương',
    hometown: 'Tiền Giang',
    date: 'Hôm nay',
    timeSlot: '09:00-10:00',
    timeSlotLabel: '09:00 – 10:00',
    carType: 'Honda CR-V (Xe 5 chỗ)',
    capacity: 3,
    availableSeats: 2,
    basePricePerSeat: 100000,
    customDiscountPercent: 0,
    depositPerSeat: 50000,
    isVip: true,
    rating: 4.92,
    completedCount: 89,
    perks: ['Chạy cao tốc Trung Lương', 'Trọn gói xăng & cầu đường'],
    notes: 'Chạy cao tốc Trung Lương, nhanh 1 tiếng. Đón tại BX Mỹ Tho.',
    createdAt: Date.now() - 3600000 * 5
  },
  {
    id: 'DRV-106',
    type: 'driver_offer',
    maskedCode: 'CX-106',
    publicName: 'Chủ xe CX-106',
    phoneReal: '0900.000.022',
    direction: 'province_to_sg',
    from: 'Biên Hòa (Ngã tư Amata / QL1K)',
    to: 'Sài Gòn (Cầu Bình Triệu / Hàng Xanh)',
    routeCategory: 'Tuyến QL1K',
    hometown: 'Đồng Nai',
    date: 'Ngày mai',
    timeSlot: '05:00-06:00',
    timeSlotLabel: '05:00 – 06:00',
    carType: 'VinFast VF8 (Xe 5 chỗ điện)',
    capacity: 3,
    availableSeats: 2,
    basePricePerSeat: 80000,
    customDiscountPercent: 0,
    depositPerSeat: 50000,
    isVip: false,
    rating: 4.8,
    completedCount: 23,
    perks: ['Xe điện êm ái', 'Không mùi xăng', 'Ghế rộng'],
    notes: 'Xe điện VinFast, êm mát, không mùi xăng. Chuyến sáng sớm, giờ giấc hai bên tự thống nhất.',
    createdAt: Date.now() - 3600000 * 2
  }
];

export const INITIAL_PASSENGER_REQUESTS = [
  {
    id: 'REQ-201',
    type: 'passenger_request',
    maskedCode: 'KX-201',
    publicName: 'Khách KX-201',
    phoneReal: '0900.000.015',
    direction: 'province_to_sg',
    from: 'Lộc Ninh (Chợ Lộc Ninh / KP Ninh Thịnh)',
    to: 'Sài Gòn (Bệnh Viện Chợ Rẫy / Quận 5)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Lộc Ninh',
    date: 'Ngày mai',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 – 08:00',
    isRecurringWeekly: true,
    seatsNeeded: 2,
    expectedPrice: 180000,
    depositPerSeat: 50000,
    notes: 'Cần ghép 2 ghế đi tái khám, sẵn sàng cọc 100k cho 2 người. Lịch sự, không say xe.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'REQ-202',
    type: 'passenger_request',
    maskedCode: 'KX-202',
    publicName: 'Khách KX-202',
    phoneReal: '0900.000.016',
    direction: 'sg_to_province',
    from: 'Sài Gòn (Ngã 4 Thủ Đức / Xa Lộ Hà Nội)',
    to: 'Bình Phước (Cổng chào TX. Bình Long / QL13)',
    routeCategory: 'Tuyến QL13',
    hometown: 'Bình Phước',
    date: 'Hôm nay',
    timeSlot: '17:00-18:00',
    timeSlotLabel: '17:00 – 18:00',
    seatsNeeded: 1,
    expectedPrice: 170000,
    depositPerSeat: 50000,
    notes: 'Cuối tuần về quê, ghép xe dọc QL13 có 1 balo nhỏ gọn gàng.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 2
  },
  {
    id: 'REQ-203',
    type: 'passenger_request',
    maskedCode: 'KX-203',
    publicName: 'Khách KX-203',
    phoneReal: '0900.000.014',
    direction: 'sg_to_province',
    from: 'Sài Gòn (Quận 7 / Crescent Mall)',
    to: 'Vũng Tàu (Bãi Sau / Tượng Chúa Kito)',
    routeCategory: 'Tuyến QL51',
    hometown: 'Vũng Tàu',
    date: 'Thứ 7',
    timeSlot: '07:00-08:00',
    timeSlotLabel: '07:00 – 08:00',
    seatsNeeded: 3,
    expectedPrice: 160000,
    depositPerSeat: 50000,
    notes: 'Gia đình 3 người đi biển cuối tuần, có 2 balo + 1 túi nhỏ.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 1
  },
  {
    id: 'REQ-204',
    type: 'passenger_request',
    maskedCode: 'KX-204',
    publicName: 'Khách KX-204',
    phoneReal: '0900.000.023',
    direction: 'sg_to_province',
    from: 'Sài Gòn (Bến xe Miền Đông mới / TP. Thủ Đức)',
    to: 'Phan Thiết (Mũi Né / Đồi Cát Bay)',
    routeCategory: 'Tuyến QL1A',
    hometown: 'Bình Thuận',
    date: 'Hôm nay',
    timeSlot: '15:00-16:00',
    timeSlotLabel: '15:00 – 16:00',
    seatsNeeded: 1,
    expectedPrice: 180000,
    depositPerSeat: 50000,
    notes: 'Sinh viên về quê, hành lý gọn.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 3
  },
  {
    id: 'REQ-205',
    type: 'passenger_request',
    maskedCode: 'KX-205',
    publicName: 'Khách KX-205',
    phoneReal: '0900.000.021',
    direction: 'sg_to_province',
    from: 'Bến xe Miền Tây (Q. Bình Tân)',
    to: 'TP Bến Tre',
    routeCategory: 'Tuyến QL60',
    hometown: 'Bến Tre',
    date: 'Hôm nay',
    timeSlot: '13:00-14:00',
    timeSlotLabel: '13:00 – 14:00',
    seatsNeeded: 2,
    expectedPrice: 120000,
    depositPerSeat: 50000,
    notes: 'Hai chị em về thăm ngoại, cần xe sạch sẽ, không mùi thuốc lá.',
    status: 'open',
    createdAt: Date.now() - 3600000 * 4
  }
];

export const INITIAL_BOOKED_ESCROWS = [];
