import React from 'react';
import { ChevronRight } from 'lucide-react';
import { priceLabel, pickupLabel, freshnessLabel } from './tripPresentation.js';

/**
 * Helper for a compact period-and-date format for the compact card
 */
function formatShortTime(departureLabel = '', departureDate = null) {
  if (!departureDate) return 'Chưa rõ ngày';
  if (!departureLabel) return departureDate;
  let hour = 4;
  if (departureLabel && departureLabel.includes(':')) {
    const [h] = departureLabel.split(':').map(Number);
    if (!isNaN(h)) hour = h;
  }
  let session = 'Sáng';
  if (hour >= 11 && hour < 14) session = 'Trưa';
  else if (hour >= 14 && hour < 18) session = 'Chiều';
  else if (hour >= 18 || hour < 4) session = 'Tối';

  if (departureDate === 'Ngày mai') {
    return `${session} mai`;
  }
  if (departureDate === 'Hôm nay' || !departureDate) {
    return `${session} nay`;
  }

  const targetDate = new Date(departureDate);
  if (!isNaN(targetDate.getTime())) {
    const d = targetDate.getDate();
    const m = targetDate.getMonth() + 1;
    return `${session} (${d}/${m})`;
  }

  return `${session} nay`;
}

/**
 * Helper that shortens pickup/drop-off station names so they display neatly on narrow screens
 */
/**
 * COMPACT TRIP CARD (~85px)
 *
 * Standard Scannable List (BlaBlaCar / Vexere Style):
 * ┌─────────────────────────────────────────────────────────────┐
 * │ 07:00    Xe 7 chỗ gia đình                 165.000 đ        │
 * │ Sáng mai Tân Khai (QL13) ➔ Chợ Rẫy/ĐHYD    Còn 2 chỗ  ›     │
 * └─────────────────────────────────────────────────────────────┘
 *
 * Passengers swipe a finger and instantly see 3-4 choices for the day, without being overwhelmed by text.
 * Tapping the row or the › icon opens the Bottom Sheet with full context & reputation details.
 */
export default function CorridorTripCard({
  trip,
  isEarliest = false,
  isMyTrip = false,
  onSelectTrip,
  onBookNow,
  onManageTrip
}) {
  if (!trip) return null;

  const seatsAvailable = trip.seatsAvailable == null ? null : Number(trip.seatsAvailable);
  const isSoldOut = seatsAvailable !== null && seatsAvailable <= 0;
  const timeSubLabel = formatShortTime(trip.departureLabel, trip.departureDate);

  const vehicleTypeLabel = trip.vehicleModel || trip.carType || 'Chưa rõ loại xe';

  // Get the real-world USP for each trip (Tufte Data-Ink)
  // Trip characteristics only show when the driver actually declares them. Previously they were generated by
  // POSITION in the list: the first trip was promised "Trả tận cổng viện" (Drop-off right at the hospital gate), the second
  // was assigned the name "Chủ xe H. (#102)" (Driver H. (#102)), and the rest were promised "Không nhồi nhét" (No overcrowding) — fabricated service commitments,
  // changing the sort order changed the vehicle's "characteristics" too.
  const uspLabel = trip.usp || '';

  const handleClick = () => {
    if (isSoldOut) return;
    if (onSelectTrip) onSelectTrip(trip);
    else if (onBookNow) onBookNow(trip);
  };

  return (
    <div
      onClick={handleClick}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          handleClick();
        }
      }}
      className={`group w-full rounded-2xl border transition-all duration-200 px-3.5 py-3 select-none type-body ${
        isSoldOut
          ? 'bg-slate-50/70 dark:bg-white/[0.02] border-slate-200 dark:border-white/10 opacity-70 cursor-not-allowed'
          : isMyTrip
          ? 'bg-emerald-50/30 dark:bg-emerald-950/20 border-emerald-400/60 dark:border-emerald-500/40 ring-1 ring-emerald-400/20 shadow-sm hover:shadow-md hover:border-emerald-500 hover:-translate-y-0.5 active:scale-[0.99] cursor-pointer'
          : isEarliest
          ? 'bg-white dark:bg-[#1c1c1e] border-slate-200 dark:border-white/15 shadow-md hover:shadow-lg hover:border-slate-300 dark:hover:border-white/25 hover:-translate-y-0.5 active:scale-[0.99] cursor-pointer'
          : 'bg-white dark:bg-[#1c1c1e] border-slate-200 dark:border-white/15 shadow-sm hover:shadow-md hover:border-slate-300 dark:hover:border-white/25 hover:-translate-y-0.5 active:scale-[0.99] cursor-pointer'
      }`}
    >
      <div className="flex items-center justify-between min-w-0 type-body">
        {/* ── Column 1: Time (Hard-locked at 58px, fits exactly) ── */}
        <div className="w-[58px] shrink-0 flex flex-col items-start type-body">
          <span className="text-slate-900 dark:text-white tabular type-heading">
            {trip.departureLabel || '—'}
          </span>
          {isMyTrip ? (
            <span className="px-1.5 py-0.5 text-emerald-900 dark:text-emerald-100 bg-emerald-400 dark:bg-emerald-500 rounded-full mt-0.5 shadow-2xs whitespace-nowrap type-badge">
              Xe của bạn
            </span>
          ) : isEarliest ? (
            <span className="px-1.5 py-0.5 text-white bg-[#0071e3] rounded-full mt-0.5 type-badge">
              Gần nhất
            </span>
          ) : (
            <span className="text-slate-500 dark:text-slate-400 mt-0.5 truncate block type-body-strong">
              {timeSubLabel}
            </span>
          )}
        </div>

        {/* ── Column 2: Vehicle info (Widened ml-2.5 mr-1 so 100% of the text unfolds fully) ── */}
        <div className="flex-1 min-w-0 ml-2.5 mr-1">
          {trip.operatorName && <p className="mb-1 truncate text-[#0071e3] dark:text-blue-300 type-body-strong">{trip.operatorName}</p>}
          <div className="text-slate-900 dark:text-white truncate flex items-center gap-1.5 type-body-strong">
            <span>{vehicleTypeLabel}</span>
          </div>
          {/* In place of fabricated "characteristics": show the trip's real drop-off point, or characteristics
              declared by the driver themselves. If there is nothing real, no line is shown. */}
          {(uspLabel || trip.toLocation) && (
            <div className="text-slate-600 dark:text-slate-400 truncate mt-0.5 type-caption">
              {uspLabel || `Trả tại ${trip.toLocation}`}
            </div>
          )}
        </div>

        {/* ── Column 3: Price & Button (Fixed on the right - shrink-0 flex items-center gap-2) ── */}
        <div className="shrink-0 flex items-center gap-2 type-body">
          <div className="text-right type-body">
            <div className="text-slate-900 dark:text-white tabular type-heading">
              {priceLabel(trip)}
            </div>
            <div className="mt-0.5 type-body">
              {isSoldOut ? (
                <span className="text-slate-400">Hết chỗ</span>
              ) : seatsAvailable === 1 ? (
                <span className="text-amber-700 dark:text-amber-400 type-body-strong">
                  Còn 1 chỗ
                </span>
              ) : (
                <span className="text-slate-500 dark:text-slate-400 type-body">
                  {seatsAvailable === null ? 'Hỏi số chỗ' : `Còn ${seatsAvailable} chỗ`}
                </span>
              )}
            </div>
          </div>

          {isMyTrip ? (
            <button
              type="button"
              tabIndex={-1}
              aria-label="Quản lý chuyến xe của bạn"
              onClick={(e) => {
                e.stopPropagation();
                if (onManageTrip) onManageTrip(trip);
                else handleClick();
              }}
              className="px-2.5 py-1.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 active:scale-95 text-slate-950 flex items-center gap-1 transition-all cursor-pointer shadow-xs shrink-0 type-button-sm"
            >
              <span>Quản lý</span>
              <ChevronRight className="w-3 h-3 stroke-[2.5]" />
            </button>
          ) : (
            <button
              type="button"
              tabIndex={-1}
              aria-label="Xem chi tiết chuyến xe"
              className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 transition-all duration-150 type-button ${
                isEarliest
                  ? 'bg-[#0071e3] text-white shadow-xs group-hover:scale-110'
                  : 'bg-slate-100 dark:bg-white/10 text-slate-600 dark:text-slate-300 group-hover:bg-[#0071e3] group-hover:text-white'
              }`}
            >
              <ChevronRight className="w-3.5 h-3.5 stroke-[2.5]" />
            </button>
          )}
        </div>
      </div>
      <p className="mt-2 text-slate-500 dark:text-slate-400 type-body">{pickupLabel(trip.pickupMode)} · {freshnessLabel(trip)}</p>
    </div>
  );
}
